version: "3.4"
services:
  winston_optl_format_tester:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: winston_optl_format_tester
    container_name: winston_optl_format_tester
    platform: linux/amd64
    volumes:
      - .:/srv/
    tty: true
    environment:
      - OTEL_SERVICE_NAME=app-main-server